name: country_code_picker
description: A flutter package for showing a country code selector. In addition it gives the possibility to select a list of favorites countries, as well as to search using a simple searchbox  
version: 1.1.5
author: Salvatore-Giordano <svtgiordano@gmail.com>
homepage: https://github.com/Salvatore-Giordano/CountryCodePicker

environment:
  sdk: ">=1.19.0  <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  assets:
    - flags/tg.svg
    - flags/me.svg
    - flags/la.svg
    - flags/mr.svg
    - flags/ni.svg
    - flags/lv.svg
    - flags/om.svg
    - flags/af.svg
    - flags/cy.svg
    - flags/bj.svg
    - flags/aq.svg
    - flags/cn.svg
    - flags/gb-sct.svg
    - flags/co.svg
    - flags/cx.svg
    - flags/ag.svg
    - flags/ms.svg
    - flags/md.svg
    - flags/zm.svg
    - flags/vn.svg
    - flags/tf.svg
    - flags/td.svg
    - flags/yt.svg
    - flags/lb.svg
    - flags/mf.svg
    - flags/lu.svg
    - flags/mq.svg
    - flags/cz.svg
    - flags/ae.svg
    - flags/cm.svg
    - flags/bi.svg
    - flags/ar.svg
    - flags/as.svg
    - flags/bh.svg
    - flags/cl.svg
    - flags/ad.svg
    - flags/mp.svg
    - flags/lt.svg
    - flags/mg.svg
    - flags/lc.svg
    - flags/tr.svg
    - flags/ua.svg
    - flags/tv.svg
    - flags/vi.svg
    - flags/mt.svg
    - flags/no.svg
    - flags/mc.svg
    - flags/ch.svg
    - flags/bl.svg
    - flags/aw.svg
    - flags/bz.svg
    - flags/bm.svg
    - flags/ci.svg
    - flags/mu.svg
    - flags/us.svg
    - flags/tw.svg
    - flags/ye.svg
    - flags/mw.svg
    - flags/nl.svg
    - flags/ls.svg
    - flags/bo.svg
    - flags/at.svg
    - flags/ck.svg
    - flags/by.svg
    - flags/au.svg
    - flags/bn.svg
    - flags/ma.svg
    - flags/nz.svg
    - flags/lr.svg
    - flags/mv.svg
    - flags/tc.svg
    - flags/ug.svg
    - flags/tt.svg
    - flags/pl.svg
    - flags/rs.svg
    - flags/in.svg
    - flags/ge.svg
    - flags/gr.svg
    - flags/gs.svg
    - flags/gd.svg
    - flags/io.svg
    - flags/hk.svg
    - flags/kp.svg
    - flags/gb-nir.svg
    - flags/kg.svg
    - flags/pm.svg
    - flags/sv.svg
    - flags/re.svg
    - flags/sa.svg
    - flags/sc.svg
    - flags/st.svg
    - flags/ke.svg
    - flags/im.svg
    - flags/kr.svg
    - flags/gf.svg
    - flags/dj.svg
    - flags/gq.svg
    - flags/gp.svg
    - flags/dk.svg
    - flags/gg.svg
    - flags/il.svg
    - flags/pn.svg
    - flags/sb.svg
    - flags/py.svg
    - flags/ru.svg
    - flags/kw.svg
    - flags/do.svg
    - flags/gt.svg
    - flags/gb.svg
    - flags/gu.svg
    - flags/je.svg
    - flags/hm.svg
    - flags/sg.svg
    - flags/pk.svg
    - flags/sr.svg
    - flags/se.svg
    - flags/jp.svg
    - flags/gw.svg
    - flags/eh.svg
    - flags/dz.svg
    - flags/ga.svg
    - flags/fr.svg
    - flags/dm.svg
    - flags/hn.svg
    - flags/sd.svg
    - flags/rw.svg
    - flags/ph.svg
    - flags/ss.svg
    - flags/qa.svg
    - flags/pe.svg
    - flags/pr.svg
    - flags/si.svg
    - flags/ht.svg
    - flags/es.svg
    - flags/gl.svg
    - flags/gm.svg
    - flags/er.svg
    - flags/fi.svg
    - flags/ee.svg
    - flags/kn.svg
    - flags/hu.svg
    - flags/iq.svg
    - flags/ky.svg
    - flags/sh.svg
    - flags/ps.svg
    - flags/pf.svg
    - flags/sj.svg
    - flags/id.svg
    - flags/is.svg
    - flags/eg.svg
    - flags/fk.svg
    - flags/fj.svg
    - flags/gn.svg
    - flags/gy.svg
    - flags/ir.svg
    - flags/km.svg
    - flags/ie.svg
    - flags/kz.svg
    - flags/ro.svg
    - flags/sk.svg
    - flags/pg.svg
    - flags/pt.svg
    - flags/so.svg
    - flags/sx.svg
    - flags/hr.svg
    - flags/ki.svg
    - flags/jm.svg
    - flags/eu.svg
    - flags/ec.svg
    - flags/et.svg
    - flags/fo.svg
    - flags/kh.svg
    - flags/sy.svg
    - flags/sn.svg
    - flags/pw.svg
    - flags/sl.svg
    - flags/gb-eng.svg
    - flags/fm.svg
    - flags/gi.svg
    - flags/de.svg
    - flags/gh.svg
    - flags/jo.svg
    - flags/it.svg
    - flags/pa.svg
    - flags/sz.svg
    - flags/sm.svg
    - flags/tn.svg
    - flags/ml.svg
    - flags/cg.svg
    - flags/ax.svg
    - flags/ao.svg
    - flags/bt.svg
    - flags/bb.svg
    - flags/cf.svg
    - flags/mm.svg
    - flags/li.svg
    - flags/na.svg
    - flags/mz.svg
    - flags/to.svg
    - flags/vg.svg
    - flags/ve.svg
    - flags/tz.svg
    - flags/tm.svg
    - flags/mx.svg
    - flags/nc.svg
    - flags/mo.svg
    - flags/lk.svg
    - flags/cd.svg
    - flags/al.svg
    - flags/bw.svg
    - flags/cr.svg
    - flags/bv.svg
    - flags/am.svg
    - flags/az.svg
    - flags/ba.svg
    - flags/mn.svg
    - flags/nu.svg
    - flags/my.svg
    - flags/tl.svg
    - flags/ws.svg
    - flags/th.svg
    - flags/xk.svg
    - flags/nf.svg
    - flags/ly.svg
    - flags/ai.svg
    - flags/br.svg
    - flags/cv.svg
    - flags/be.svg
    - flags/ca.svg
    - flags/bd.svg
    - flags/cw.svg
    - flags/bs.svg
    - flags/ng.svg
    - flags/mk.svg
    - flags/np.svg
    - flags/va.svg
    - flags/uz.svg
    - flags/um.svg
    - flags/tk.svg
    - flags/vc.svg
    - flags/zw.svg
    - flags/nr.svg
    - flags/ne.svg
    - flags/cu.svg
    - flags/bq.svg
    - flags/bf.svg
    - flags/bg.svg
    - flags/cc.svg
    - flags/gb-wls.svg
    - flags/mh.svg
    - flags/za.svg
    - flags/uy.svg
    - flags/wf.svg
    - flags/vu.svg
    - flags/tj.svg
    - flags/an.svg
