List<Map> countryCodes = [
  {"name": "Afghanistan", "code": "AF", "dial_code": "+93"},
  {"name": "Aland Islands", "code": "AX", "dial_code": "+358"},
  {"name": "Albania", "code": "AL", "dial_code": "+355"},
  {"name": "Algeria", "code": "DZ", "dial_code": "+213"},
  {"name": "American Samoa", "code": "AS", "dial_code": "+1684"},
  {"name": "Andorra", "code": "AD", "dial_code": "+376"},
  {"name": "Angola", "code": "AO", "dial_code": "+244"},
  {"name": "Anguilla", "code": "AI", "dial_code": "+1264"},
  {"name": "Antarctica", "code": "AQ", "dial_code": "+672"},
  {"name": "Antigua and Barbuda", "code": "AG", "dial_code": "+1268"},
  {"name": "Argentina", "code": "AR", "dial_code": "+54"},
  {"name": "Armenia", "code": "AM", "dial_code": "+374"},
  {"name": "Aruba", "code": "AW", "dial_code": "+297"},
  {"name": "Australia", "code": "AU", "dial_code": "+61"},
  {"name": "Austria", "code": "AT", "dial_code": "+43"},
  {"name": "Azerbaijan", "code": "AZ", "dial_code": "+994"},
  {"name": "Bahamas", "code": "BS", "dial_code": "+1242"},
  {"name": "Bahrain", "code": "BH", "dial_code": "+973"},
  {"name": "Bangladesh", "code": "BD", "dial_code": "+880"},
  {"name": "Barbados", "code": "BB", "dial_code": "+1246"},
  {"name": "Belarus", "code": "BY", "dial_code": "+375"},
  {"name": "Belgium", "code": "BE", "dial_code": "+32"},
  {"name": "Belize", "code": "BZ", "dial_code": "+501"},
  {"name": "Benin", "code": "BJ", "dial_code": "+229"},
  {"name": "Bermuda", "code": "BM", "dial_code": "+1441"},
  {"name": "Bhutan", "code": "BT", "dial_code": "+975"},
  {"name": "Bolivia", "code": "BO", "dial_code": "+591"},
  {"name": "Bosnia and Herzegovina", "code": "BA", "dial_code": "+387"},
  {"name": "Botswana", "code": "BW", "dial_code": "+267"},
  {"name": "Bouvet Island", "code": "BV", "dial_code": "+47"},
  {"name": "Brazil", "code": "BR", "dial_code": "+55"},
  {"name": "British Indian Ocean Territory", "code": "IO", "dial_code": "+246"},
  {"name": "Brunei", "code": "BN", "dial_code": "+673"},
  {"name": "Bulgaria", "code": "BG", "dial_code": "+359"},
  {"name": "Burkina Faso", "code": "BF", "dial_code": "+226"},
  {"name": "Burundi", "code": "BI", "dial_code": "+257"},
  {"name": "Cambodia", "code": "KH", "dial_code": "+855"},
  {"name": "Cameroon", "code": "CM", "dial_code": "+237"},
  {"name": "Canada", "code": "CA", "dial_code": "+1"},
  {"name": "Cabo Verde", "code": "CV", "dial_code": "+238"},
  {"name": "Cayman Islands", "code": "KY", "dial_code": "+ 345"},
  {"name": "Central African Republic", "code": "CF", "dial_code": "+236"},
  {"name": "Chad", "code": "TD", "dial_code": "+235"},
  {"name": "Chile", "code": "CL", "dial_code": "+56"},
  {"name": "China", "code": "CN", "dial_code": "+86"},
  {"name": "Christmas Island", "code": "CX", "dial_code": "+61"},
  {"name": "Cocos (Keeling) Islands", "code": "CC", "dial_code": "+61"},
  {"name": "Colombia", "code": "CO", "dial_code": "+57"},
  {"name": "Komori", "code": "KM", "dial_code": "+269"},
  {"name": "Republic of the Congo", "code": "CG", "dial_code": "+242"},
  {
    "name": "Democratic Republic of the Congo",
    "code": "CD",
    "dial_code": "+243"
  },
  {"name": "Cook Islands", "code": "CK", "dial_code": "+682"},
  {"name": "Costa Rica", "code": "CR", "dial_code": "+506"},
  {"name": "Ivory Coast", "code": "CI", "dial_code": "+225"},
  {"name": "Croatia", "code": "HR", "dial_code": "+385"},
  {"name": "Cuba", "code": "CU", "dial_code": "+53"},
  {"name": "Cyprus", "code": "CY", "dial_code": "+357"},
  {"name": "Czech Republic", "code": "CZ", "dial_code": "+420"},
  {"name": "Danmark", "code": "DK", "dial_code": "+45"},
  {"name": "Djibouti", "code": "DJ", "dial_code": "+253"},
  {"name": "Dominica", "code": "DM", "dial_code": "+1767"},
  {"name": "Dominican Republic", "code": "DO", "dial_code": "+1849"},
  {"name": "Ecuador", "code": "EC", "dial_code": "+593"},
  {"name": "Egypt", "code": "EG", "dial_code": "+20"},
  {"name": "El Salvador", "code": "SV", "dial_code": "+503"},
  {"name": "Guinea Ecuatorial", "code": "GQ", "dial_code": "+240"},
  {"name": "Eritrea", "code": "ER", "dial_code": "+291"},
  {"name": "Estonia", "code": "EE", "dial_code": "+372"},
  {"name": "Ethiopia", "code": "ET", "dial_code": "+251"},
  {"name": "Falkland Islands", "code": "FK", "dial_code": "+500"},
  {"name": "Faroe Islands", "code": "FO", "dial_code": "+298"},
  {"name": "Fiji", "code": "FJ", "dial_code": "+679"},
  {"name": "Suomi", "code": "FI", "dial_code": "+358"},
  {"name": "France", "code": "FR", "dial_code": "+33"},
  {"name": "French Guiana", "code": "GF", "dial_code": "+594"},
  {"name": "French Polynesia", "code": "PF", "dial_code": "+689"},
  {
    "name": "French Southern Territories",
    "code": "TF",
    "dial_code": "+262"
  },
  {"name": "Gabon", "code": "GA", "dial_code": "+241"},
  {"name": "Gambia", "code": "GM", "dial_code": "+220"},
  {"name": "Georgia", "code": "GE", "dial_code": "+995"},
  {"name": "Germany", "code": "DE", "dial_code": "+49"},
  {"name": "Ghana", "code": "GH", "dial_code": "+233"},
  {"name": "Gibraltar", "code": "GI", "dial_code": "+350"},
  {"name": "Greece", "code": "GR", "dial_code": "+30"},
  {"name": "Greenland", "code": "GL", "dial_code": "+299"},
  {"name": "Grenada", "code": "GD", "dial_code": "+1473"},
  {"name": "Guadeloupe", "code": "GP", "dial_code": "+590"},
  {"name": "Guam", "code": "GU", "dial_code": "+1671"},
  {"name": "Guatemala", "code": "GT", "dial_code": "+502"},
  {"name": "Guernsey", "code": "GG", "dial_code": "+44"},
  {"name": "Guinea", "code": "GN", "dial_code": "+224"},
  {"name": "Guinea-Bissau", "code": "GW", "dial_code": "+245"},
  {"name": "Guyana", "code": "GY", "dial_code": "+592"},
  {"name": "Haiti", "code": "HT", "dial_code": "+509"},
  {
    "name": "Heard Island and McDonald Islands",
    "code": "HM",
    "dial_code": "+0"
  },
  {"name": "Vatican", "code": "VA", "dial_code": "+379"},
  {"name": "Honduras", "code": "HN", "dial_code": "+504"},
  {"name": "Hong Kong", "code": "HK", "dial_code": "+852"},
  {"name": "Hungary", "code": "HU", "dial_code": "+36"},
  {"name": "Iceland", "code": "IS", "dial_code": "+354"},
  {"name": "India", "code": "IN", "dial_code": "+91"},
  {"name": "Indonesia", "code": "ID", "dial_code": "+62"},
  {"name": "Iran", "code": "IR", "dial_code": "+98"},
  {"name": "Iraq", "code": "IQ", "dial_code": "+964"},
  {"name": "Ireland", "code": "IE", "dial_code": "+353"},
  {"name": "Isle of Man", "code": "IM", "dial_code": "+44"},
  {"name": "Israel", "code": "IL", "dial_code": "+972"},
  {"name": "Italia", "code": "IT", "dial_code": "+39"},
  {"name": "Jamaica", "code": "JM", "dial_code": "+1876"},
  {"name": "Japan", "code": "JP", "dial_code": "+81"},
  {"name": "Jersey", "code": "JE", "dial_code": "+44"},
  {"name": "Jordan", "code": "JO", "dial_code": "+962"},
  {"name": "Kazakhstan", "code": "KZ", "dial_code": "+7"},
  {"name": "Kenya", "code": "KE", "dial_code": "+254"},
  {"name": "Kiribati", "code": "KI", "dial_code": "+686"},
  {"name": "North Korea", "code": "KP", "dial_code": "+850"},
  {"name": "South Korea", "code": "KR", "dial_code": "+82"},
  {"name": "Kosovo", "code": "XK", "dial_code": "+383"},
  {"name": "Kuwait", "code": "KW", "dial_code": "+965"},
  {"name": "Kyrgyzstan", "code": "KG", "dial_code": "+996"},
  {"name": "Laos", "code": "LA", "dial_code": "+856"},
  {"name": "Latvia", "code": "LV", "dial_code": "+371"},
  {"name": "Lebanon", "code": "LB", "dial_code": "+961"},
  {"name": "Lesotho", "code": "LS", "dial_code": "+266"},
  {"name": "Liberia", "code": "LR", "dial_code": "+231"},
  {"name": "Libya", "code": "LY", "dial_code": "+218"},
  {"name": "Liechtenstein", "code": "LI", "dial_code": "+423"},
  {"name": "Lietuva", "code": "LT", "dial_code": "+370"},
  {"name": "Luxembourg", "code": "LU", "dial_code": "+352"},
  {"name": "Macao", "code": "MO", "dial_code": "+853"},
  {"name": "Macedonia", "code": "MK", "dial_code": "+389"},
  {"name": "Madagascar", "code": "MG", "dial_code": "+261"},
  {"name": "Malawi", "code": "MW", "dial_code": "+265"},
  {"name": "Malaysia", "code": "MY", "dial_code": "+60"},
  {"name": "Maldives", "code": "MV", "dial_code": "+960"},
  {"name": "Mali", "code": "ML", "dial_code": "+223"},
  {"name": "Malta", "code": "MT", "dial_code": "+356"},
  {"name": "Marshall Islands", "code": "MH", "dial_code": "+692"},
  {"name": "Martinique", "code": "MQ", "dial_code": "+596"},
  {"name": "Mauritania", "code": "MR", "dial_code": "+222"},
  {"name": "Mauritius", "code": "MU", "dial_code": "+230"},
  {"name": "Mayotte", "code": "YT", "dial_code": "+262"},
  {"name": "Mexico", "code": "MX", "dial_code": "+52"},
  {"name": "Micronesia", "code": "FM", "dial_code": "+691"},
  {"name": "Moldova", "code": "MD", "dial_code": "+373"},
  {"name": "Monaco", "code": "MC", "dial_code": "+377"},
  {"name": "Mongolia", "code": "MN", "dial_code": "+976"},
  {"name": "Montenegro", "code": "ME", "dial_code": "+382"},
  {"name": "Montserrat", "code": "MS", "dial_code": "+1664"},
  {"name": "Morocco", "code": "MA", "dial_code": "+212"},
  {"name": "Mozambique", "code": "MZ", "dial_code": "+258"},
  {"name": "Myanma", "code": "MM", "dial_code": "+95"},
  {"name": "Namibia", "code": "NA", "dial_code": "+264"},
  {"name": "Nauru", "code": "NR", "dial_code": "+674"},
  {"name": "Nepal", "code": "NP", "dial_code": "+977"},
  {"name": "Nederland", "code": "NL", "dial_code": "+31"},
  {"name": "Nouvelle-Calédonie", "code": "NC", "dial_code": "+687"},
  {"name": "New Zealand", "code": "NZ", "dial_code": "+64"},
  {"name": "Nicaragua", "code": "NI", "dial_code": "+505"},
  {"name": "Niger", "code": "NE", "dial_code": "+227"},
  {"name": "Nigeria", "code": "NG", "dial_code": "+234"},
  {"name": "Niue", "code": "NU", "dial_code": "+683"},
  {"name": "Norfolk Island", "code": "NF", "dial_code": "+672"},
  {"name": "Northern Mariana Islands", "code": "MP", "dial_code": "+1670"},
  {"name": "Norge", "code": "NO", "dial_code": "+47"},
  {"name": "Oman", "code": "OM", "dial_code": "+968"},
  {"name": "Pakistan", "code": "PK", "dial_code": "+92"},
  {"name": "Palau", "code": "PW", "dial_code": "+680"},
  {"name": "Palestinian Territory", "code": "PS", "dial_code": "+970"},
  {"name": "Panamá", "code": "PA", "dial_code": "+507"},
  {"name": "Papua Niugini", "code": "PG", "dial_code": "+675"},
  {"name": "Paraguay", "code": "PY", "dial_code": "+595"},
  {"name": "Peru", "code": "PE", "dial_code": "+51"},
  {"name": "Pilipinas", "code": "PH", "dial_code": "+63"},
  {"name": "Pitcairn Islands", "code": "PN", "dial_code": "+64"},
  {"name": "Polska", "code": "PL", "dial_code": "+48"},
  {"name": "Portugal", "code": "PT", "dial_code": "+351"},
  {"name": "Puerto Rico", "code": "PR", "dial_code": "+1939"},
  {"name": "Qatar", "code": "QA", "dial_code": "+974"},
  {"name": "Romania", "code": "RO", "dial_code": "+40"},
  {"name": "Russia", "code": "RU", "dial_code": "+7"},
  {"name": "Rwanda", "code": "RW", "dial_code": "+250"},
  {"name": "Reunion", "code": "RE", "dial_code": "+262"},
  {"name": "Saint Barthelemy", "code": "BL", "dial_code": "+590"},
  {"name": "Saint Helena", "code": "SH", "dial_code": "+290"},
  {"name": "Saint Kitts and Nevis", "code": "KN", "dial_code": "+1869"},
  {"name": "Saint Lucia", "code": "LC", "dial_code": "+1758"},
  {"name": "Saint-Martin", "code": "MF", "dial_code": "+590"},
  {"name": "Saint-Pierre-et-Miquelon", "code": "PM", "dial_code": "+508"},
  {
    "name": "Saint Vincent and the Grenadines",
    "code": "VC",
    "dial_code": "+1784"
  },
  {"name": "Samoa", "code": "WS", "dial_code": "+685"},
  {"name": "San Marino", "code": "SM", "dial_code": "+378"},
  {"name": "São Tomé e Príncipe", "code": "ST", "dial_code": "+239"},
  {"name": "Saudi Arabia", "code": "SA", "dial_code": "+966"},
  {"name": "Senegal", "code": "SN", "dial_code": "+221"},
  {"name": "Serbia", "code": "RS", "dial_code": "+381"},
  {"name": "Seychelles", "code": "SC", "dial_code": "+248"},
  {"name": "Sierra Leone", "code": "SL", "dial_code": "+232"},
  {"name": "Singapore", "code": "SG", "dial_code": "+65"},
  {"name": "Slovensko", "code": "SK", "dial_code": "+421"},
  {"name": "Slovenija", "code": "SI", "dial_code": "+386"},
  {"name": "Solomon Islands", "code": "SB", "dial_code": "+677"},
  {"name": "Somalia", "code": "SO", "dial_code": "+252"},
  {"name": "South Africa", "code": "ZA", "dial_code": "+27"},
  {"name": "South Sudan", "code": "SS", "dial_code": "+211"},
  {"name": "South Georgia", "code": "GS", "dial_code": "+500"},
  {"name": "España", "code": "ES", "dial_code": "+34"},
  {"name": "Sri Lanka", "code": "LK", "dial_code": "+94"},
  {"name": "Sudan", "code": "SD", "dial_code": "+249"},
  {"name": "Suriname", "code": "SR", "dial_code": "+597"},
  {"name": "Svalbard og Jan Mayen", "code": "SJ", "dial_code": "+47"},
  {"name": "Swaziland", "code": "SZ", "dial_code": "+268"},
  {"name": "Sverige", "code": "SE", "dial_code": "+46"},
  {"name": "Schweiz", "code": "CH", "dial_code": "+41"},
  {"name": "Syria", "code": "SY", "dial_code": "+963"},
  {"name": "Taiwan", "code": "TW", "dial_code": "+886"},
  {"name": "Tajikistan", "code": "TJ", "dial_code": "+992"},
  {"name": "Tanzania", "code": "TZ", "dial_code": "+255"},
  {"name": "Thailand", "code": "TH", "dial_code": "+66"},
  {"name": "Timor-Leste", "code": "TL", "dial_code": "+670"},
  {"name": "Togo", "code": "TG", "dial_code": "+228"},
  {"name": "Tokelau", "code": "TK", "dial_code": "+690"},
  {"name": "Tonga", "code": "TO", "dial_code": "+676"},
  {"name": "Trinidad and Tobago", "code": "TT", "dial_code": "+1868"},
  {"name": "Tunisia", "code": "TN", "dial_code": "+216"},
  {"name": "Turkey", "code": "TR", "dial_code": "+90"},
  {"name": "Turkmenistan", "code": "TM", "dial_code": "+993"},
  {"name": "Turks and Caicos Islands", "code": "TC", "dial_code": "+1649"},
  {"name": "Tuvalu", "code": "TV", "dial_code": "+688"},
  {"name": "Uganda", "code": "UG", "dial_code": "+256"},
  {"name": "Ukraine", "code": "UA", "dial_code": "+380"},
  {"name": "United Arab Emirates", "code": "AE", "dial_code": "+971"},
  {"name": "United Kingdom", "code": "GB", "dial_code": "+44"},
  {"name": "United States", "code": "US", "dial_code": "+1"},
  {"name": "Uruguay", "code": "UY", "dial_code": "+598"},
  {"name": "Uzbekistan", "code": "UZ", "dial_code": "+998"},
  {"name": "Vanuatu", "code": "VU", "dial_code": "+678"},
  {"name": "Venezuela", "code": "VE", "dial_code": "+58"},
  {"name": "Vietnam", "code": "VN", "dial_code": "+84"},
  {"name": "British Virgin Islands", "code": "VG", "dial_code": "+1284"},
  {"name": "United States Virgin Islands", "code": "VI", "dial_code": "+1340"},
  {"name": "Wallis et Futuna", "code": "WF", "dial_code": "+681"},
  {"name": "Yemen", "code": "YE", "dial_code": "+967"},
  {"name": "Zambia", "code": "ZM", "dial_code": "+260"},
  {"name": "Zimbabwe", "code": "ZW", "dial_code": "+263"}
];

var countryCurrencies = {
  "BD": {"countryName": "Bangladesh", "currency": "BDT", "symbol": "Tk"},
  "BE": {"countryName": "Belgium", "currency": "BEL", "symbol": "€"},
  "BF": {"countryName": "Burkina Faso", "currency": "XOF", "symbol": "CFA"},
  "BG": {"countryName": "Bulgaria", "currency": "BGN", "symbol": "BGN"},
  "BA": {"countryName": "Bosnia and Herzegovina", "currency": "BAM", "symbol": "KM"},
  "BB": {"countryName": "Barbados", "currency": "BBD", "symbol": "BBD"},
  "WF": {"countryName": "Wallis and Futuna", "currency": "XPF", "symbol": "XPF"},
  "BL": {"countryName": "Saint Barthelemy", "currency": "EUR", "symbol": "€"},
  "BM": {"countryName": "Bermuda", "currency": "BMD", "symbol": "BMD"},
  "BN": {"countryName": "Brunei", "currency": "BND", "symbol": "BN\$"},
  "BO": {"countryName": "Bolivia", "currency": "BOB", "symbol": "Bs"},
  "BH": {"countryName": "Bahrain", "currency": "BHD", "symbol": "BD"},
  "BI": {"countryName": "Burundi", "currency": "BIF", "symbol": "FBu"},
  "BJ": {"countryName": "Benin", "currency": "XOF", "symbol": "CFA"},
  "BT": {"countryName": "Bhutan", "currency": "BTN", "symbol": "BTN"},
  "JM": {"countryName": "Jamaica", "currency": "JMD", "symbol": "J\$"},
  "BV": {"countryName": "Bouvet Island", "currency": "NOK", "symbol": "Nkr"},
  "BW": {"countryName": "Botswana", "currency": "BWP", "symbol": "BWP"},
  "WS": {"countryName": "Samoa", "currency": "WST", "symbol": "WST"},
  "BQ": {
    "countryName": "Bonaire, Saint Eustatius and Saba ",
    "currency": "USD",
    "symbol": "\$"
  },
  "BR": {"countryName": "Brazil", "currency": "BRL", "symbol": "R\$"},
  "BS": {"countryName": "Bahamas", "currency": "BSD", "symbol": "BSD"},
  "JE": {"countryName": "Jersey", "currency": "GBP", "symbol": "£"},
  "BY": {"countryName": "Belarus", "currency": "BYR", "symbol": "BYR"},
  "BZ": {"countryName": "Belize", "currency": "BZD", "symbol": "BZ\$"},
  "RU": {"countryName": "Russia", "currency": "RUB", "symbol": "RUB"},
  "RW": {"countryName": "Rwanda", "currency": "RWF", "symbol": "RWF"},
  "RS": {"countryName": "Serbia", "currency": "RSD", "symbol": "din."},
  "TL": {"countryName": "East Timor", "currency": "USD", "symbol": "\$"},
  "RE": {"countryName": "Reunion", "currency": "EUR", "symbol": "€"},
  "TM": {"countryName": "Turkmenistan", "currency": "TMT", "symbol": "TMT"},
  "TJ": {"countryName": "Tajikistan", "currency": "TJS", "symbol": "TJS"},
  "RO": {"countryName": "Romania", "currency": "RON", "symbol": "RON"},
  "TK": {"countryName": "Tokelau", "currency": "NZD", "symbol": "NZ\$"},
  "GW": {"countryName": "Guinea-Bissau", "currency": "XOF", "symbol": "CFA"},
  "GU": {"countryName": "Guam", "currency": "USD", "symbol": "\$"},
  "GT": {"countryName": "Guatemala", "currency": "GTQ", "symbol": "GTQ"},
  "GS": {
    "countryName": "South Georgia and the South Sandwich Islands",
    "currency": "GBP",
    "symbol": "£"
  },
  "GR": {"countryName": "Greece", "currency": "EUR", "symbol": "€"},
  "GQ": {"countryName": "Equatorial Guinea", "currency": "XAF", "symbol": "FCFA"},
  "GP": {"countryName": "Guadeloupe", "currency": "EUR", "symbol": "€"},
  "JP": {"countryName": "Japan", "currency": "JPY", "symbol": "¥"},
  "GY": {"countryName": "Guyana", "currency": "GYD", "symbol": "GYD"},
  "GG": {"countryName": "Guernsey", "currency": "GBP", "symbol": "£"},
  "GF": {"countryName": "French Guiana", "currency": "EUR", "symbol": "€"},
  "GE": {"countryName": "Georgia", "currency": "GEL", "symbol": "GEL"},
  "GD": {"countryName": "Grenada", "currency": "XCD", "symbol": "XCD"},
  "GB": {"countryName": "United Kingdom", "currency": "GBP", "symbol": "£"},
  "GA": {"countryName": "Gabon", "currency": "XAF", "symbol": "FCFA"},
  "SV": {"countryName": "El Salvador", "currency": "USD", "symbol": "\$"},
  "GN": {"countryName": "Guinea", "currency": "GNF", "symbol": "FG"},
  "GM": {"countryName": "Gambia", "currency": "GMD", "symbol": "GMD"},
  "GL": {"countryName": "Greenland", "currency": "DKK", "symbol": "Dkr"},
  "GI": {"countryName": "Gibraltar", "currency": "GIP", "symbol": "GIP"},
  "GH": {"countryName": "Ghana", "currency": "GHS", "symbol": "GH₵"},
  "OM": {"countryName": "Oman", "currency": "OMR", "symbol": "OMR"},
  "TN": {"countryName": "Tunisia", "currency": "TND", "symbol": "DT"},
  "JO": {"countryName": "Jordan", "currency": "JOD", "symbol": "JD"},
  "HR": {"countryName": "Croatia", "currency": "HRK", "symbol": "kn"},
  "HT": {"countryName": "Haiti", "currency": "HTG", "symbol": "HTG"},
  "HU": {"countryName": "Hungary", "currency": "HUF", "symbol": "Ft"},
  "HK": {"countryName": "Hong Kong", "currency": "HKD", "symbol": "HK\$"},
  "HN": {"countryName": "Honduras", "currency": "HNL", "symbol": "HNL"},
  "HM": {
    "countryName": "Heard Island and McDonald Islands",
    "currency": "AUD",
    "symbol": "AU\$"
  },
  "VE": {"countryName": "Venezuela", "currency": "VEF", "symbol": "Bs.F."},
  "PR": {"countryName": "Puerto Rico", "currency": "USD", "symbol": "\$"},
  "PS": {"countryName": "Palestinian Territory", "currency": "ILS", "symbol": "₪"},
  "PW": {"countryName": "Palau", "currency": "USD", "symbol": "\$"},
  "PT": {"countryName": "Portugal", "currency": "EUR", "symbol": "€"},
  "SJ": {"countryName": "Svalbard and Jan Mayen", "currency": "NOK", "symbol": "Nkr"},
  "PY": {"countryName": "Paraguay", "currency": "PYG", "symbol": "₲"},
  "IQ": {"countryName": "Iraq", "currency": "IQD", "symbol": "IQD"},
  "PA": {"countryName": "Panama", "currency": "PAB", "symbol": "B/."},
  "PF": {"countryName": "French Polynesia", "currency": "XPF", "symbol": "XPF"},
  "PG": {"countryName": "Papua New Guinea", "currency": "PGK", "symbol": "PGK"},
  "PE": {"countryName": "Peru", "currency": "PEN", "symbol": "S/."},
  "PK": {"countryName": "Pakistan", "currency": "PKR", "symbol": "PKRs"},
  "PH": {"countryName": "Philippines", "currency": "PHP", "symbol": "₱"},
  "PN": {"countryName": "Pitcairn", "currency": "NZD", "symbol": "NZ\$"},
  "PL": {"countryName": "Poland", "currency": "PLN", "symbol": "zł"},
  "PM": {"countryName": "Saint Pierre and Miquelon", "currency": "EUR", "symbol": "€"},
  "ZM": {"countryName": "Zambia", "currency": "ZMK", "symbol": "ZK"},
  "EH": {"countryName": "Western Sahara", "currency": "MAD", "symbol": "MAD"},
  "EE": {"countryName": "Estonia", "currency": "EUR", "symbol": "€"},
  "EG": {"countryName": "Egypt", "currency": "EGP", "symbol": "EGP"},
  "ZA": {"countryName": "South Africa", "currency": "ZAR", "symbol": "R"},
  "EC": {"countryName": "Ecuador", "currency": "USD", "symbol": "\$"},
  "IT": {"countryName": "Italy", "currency": "EUR", "symbol": "€"},
  "VN": {"countryName": "Vietnam", "currency": "VND", "symbol": "₫"},
  "SB": {"countryName": "Solomon Islands", "currency": "SBD", "symbol": "SBD"},
  "ET": {"countryName": "Ethiopia", "currency": "ETB", "symbol": "Br"},
  "SO": {"countryName": "Somalia", "currency": "SOS", "symbol": "Ssh"},
  "ZW": {"countryName": "Zimbabwe", "currency": "ZWL", "symbol": "ZWL"},
  "SA": {"countryName": "Saudi Arabia", "currency": "SAR", "symbol": "SR"},
  "ES": {"countryName": "Spain", "currency": "EUR", "symbol": "€"},
  "ER": {"countryName": "Eritrea", "currency": "ERN", "symbol": "Nfk"},
  "ME": {"countryName": "Montenegro", "currency": "EUR", "symbol": "€"},
  "MD": {"countryName": "Moldova", "currency": "MDL", "symbol": "MDL"},
  "MG": {"countryName": "Madagascar", "currency": "MGA", "symbol": "MGA"},
  "MF": {"countryName": "Saint Martin", "currency": "EUR", "symbol": "€"},
  "MA": {"countryName": "Morocco", "currency": "MAD", "symbol": "MAD"},
  "MC": {"countryName": "Monaco", "currency": "EUR", "symbol": "€"},
  "UZ": {"countryName": "Uzbekistan", "currency": "UZS", "symbol": "UZS"},
  "MM": {"countryName": "Myanmar", "currency": "MMK", "symbol": "MMK"},
  "ML": {"countryName": "Mali", "currency": "XOF", "symbol": "CFA"},
  "MO": {"countryName": "Macao", "currency": "MOP", "symbol": "MOP\$"},
  "MN": {"countryName": "Mongolia", "currency": "MNT", "symbol": "MNT"},
  "MH": {"countryName": "Marshall Islands", "currency": "USD", "symbol": "\$"},
  "MK": {"countryName": "Macedonia", "currency": "MKD", "symbol": "MKD"},
  "MU": {"countryName": "Mauritius", "currency": "MUR", "symbol": "MURs"},
  "MT": {"countryName": "Malta", "currency": "EUR", "symbol": "€"},
  "MW": {"countryName": "Malawi", "currency": "MWK", "symbol": "MWK"},
  "MV": {"countryName": "Maldives", "currency": "MVR", "symbol": "MVR"},
  "MQ": {"countryName": "Martinique", "currency": "EUR", "symbol": "€"},
  "MP": {"countryName": "Northern Mariana Islands", "currency": "USD", "symbol": "\$"},
  "MS": {"countryName": "Montserrat", "currency": "XCD", "symbol": "XCD"},
  "MR": {"countryName": "Mauritania", "currency": "MRO", "symbol": "MRO"},
  "IM": {"countryName": "Isle of Man", "currency": "GBP", "symbol": "£"},
  "UG": {"countryName": "Uganda", "currency": "UGX", "symbol": "USh"},
  "TZ": {"countryName": "Tanzania", "currency": "TZS", "symbol": "TSh"},
  "MY": {"countryName": "Malaysia", "currency": "MYR", "symbol": "RM"},
  "MX": {"countryName": "Mexico", "currency": "MXN", "symbol": "MX\$"},
  "IL": {"countryName": "Israel", "currency": "ILS", "symbol": "₪"},
  "FR": {"countryName": "France", "currency": "EUR", "symbol": "€"},
  "IO": {
    "countryName": "British Indian Ocean Territory",
    "currency": "USD",
    "symbol": "\$"
  },
  "SH": {"countryName": "Saint Helena", "currency": "SHP", "symbol": "SHP"},
  "FI": {"countryName": "Finland", "currency": "EUR", "symbol": "€"},
  "FJ": {"countryName": "Fiji", "currency": "FJD", "symbol": "FJD"},
  "FK": {"countryName": "Falkland Islands", "currency": "FKP", "symbol": "FKP"},
  "FM": {"countryName": "Micronesia", "currency": "USD", "symbol": "\$"},
  "FO": {"countryName": "Faroe Islands", "currency": "DKK", "symbol": "Dkr"},
  "NI": {"countryName": "Nicaragua", "currency": "NIO", "symbol": "C\$"},
  "NL": {"countryName": "Netherlands", "currency": "EUR", "symbol": "€"},
  "NO": {"countryName": "Norway", "currency": "NOK", "symbol": "Nkr"},
  "NA": {"countryName": "Namibia", "currency": "NAD", "symbol": "N\$"},
  "VU": {"countryName": "Vanuatu", "currency": "VUV", "symbol": "VUV"},
  "NC": {"countryName": "New Caledonia", "currency": "XPF", "symbol": "XPF"},
  "NE": {"countryName": "Niger", "currency": "XOF", "symbol": "CFA"},
  "NF": {"countryName": "Norfolk Island", "currency": "AUD", "symbol": "AU\$"},
  "NG": {"countryName": "Nigeria", "currency": "NGN", "symbol": "₦"},
  "NZ": {"countryName": "New Zealand", "currency": "NZD", "symbol": "NZ\$"},
  "NP": {"countryName": "Nepal", "currency": "NPR", "symbol": "NPRs"},
  "NR": {"countryName": "Nauru", "currency": "AUD", "symbol": "AU\$"},
  "NU": {"countryName": "Niue", "currency": "NZD", "symbol": "NZ\$"},
  "CK": {"countryName": "Cook Islands", "currency": "NZD", "symbol": "NZ\$"},
  "XK": {"countryName": "Kosovo", "currency": "EUR", "symbol": "€"},
  "CI": {"countryName": "Ivory Coast", "currency": "XOF", "symbol": "CFA"},
  "CH": {"countryName": "Switzerland", "currency": "CHF", "symbol": "CHF"},
  "CO": {"countryName": "Colombia", "currency": "COP", "symbol": "CO\$"},
  "CN": {"countryName": "China", "currency": "CNY", "symbol": "CN¥"},
  "CM": {"countryName": "Cameroon", "currency": "XAF", "symbol": "FCFA"},
  "CL": {"countryName": "Chile", "currency": "CLP", "symbol": "CL\$"},
  "CC": {"countryName": "Cocos Islands", "currency": "AUD", "symbol": "AU\$"},
  "CA": {"countryName": "Canada", "currency": "CAD", "symbol": "CA\$"},
  "CG": {"countryName": "Republic of the Congo", "currency": "XAF", "symbol": "FCFA"},
  "CF": {"countryName": "Central African Republic", "currency": "XAF", "symbol": "FCFA"},
  "CD": {
    "countryName": "Democratic Republic of the Congo",
    "currency": "CDF",
    "symbol": "CDF"
  },
  "CZ": {"countryName": "Czech Republic", "currency": "CZK", "symbol": "Kč"},
  "CY": {"countryName": "Cyprus", "currency": "EUR", "symbol": "€"},
  "CX": {"countryName": "Christmas Island", "currency": "AUD", "symbol": "AU\$"},
  "CR": {"countryName": "Costa Rica", "currency": "CRC", "symbol": "₡"},
  "CW": {"countryName": "Curacao", "currency": "ANG", "symbol": "ANG"},
  "CV": {"countryName": "Cape Verde", "currency": "CVE", "symbol": "CV\$"},
  "CU": {"countryName": "Cuba", "currency": "CUP", "symbol": "CUP"},
  "SZ": {"countryName": "Swaziland", "currency": "SZL", "symbol": "SZL"},
  "SY": {"countryName": "Syria", "currency": "SYP", "symbol": "SY£"},
  "SX": {"countryName": "Sint Maarten", "currency": "ANG", "symbol": "ANG"},
  "KG": {"countryName": "Kyrgyzstan", "currency": "KGS", "symbol": "KGS"},
  "KE": {"countryName": "Kenya", "currency": "KES", "symbol": "KSH"},
  "SS": {"countryName": "South Sudan", "currency": "SSP", "symbol": "SSP"},
  "SR": {"countryName": "Suriname", "currency": "SRD", "symbol": "SRD"},
  "KI": {"countryName": "Kiribati", "currency": "AUD", "symbol": "AU\$"},
  "KH": {"countryName": "Cambodia", "currency": "KHR", "symbol": "KHR"},
  "KN": {"countryName": "Saint Kitts and Nevis", "currency": "XCD", "symbol": "XCD"},
  "KM": {"countryName": "Comoros", "currency": "KMF", "symbol": "CF"},
  "ST": {"countryName": "Sao Tome and Principe", "currency": "STD", "symbol": "STD"},
  "SK": {"countryName": "Slovakia", "currency": "EUR", "symbol": "€"},
  "KR": {"countryName": "South Korea", "currency": "KRW", "symbol": "₩"},
  "SI": {"countryName": "Slovenia", "currency": "EUR", "symbol": "€"},
  "KP": {"countryName": "North Korea", "currency": "KPW", "symbol": "KPW"},
  "KW": {"countryName": "Kuwait", "currency": "KWD", "symbol": "KD"},
  "SN": {"countryName": "Senegal", "currency": "XOF", "symbol": "CFA"},
  "SM": {"countryName": "San Marino", "currency": "EUR", "symbol": "€"},
  "SL": {"countryName": "Sierra Leone", "currency": "SLL", "symbol": "SLL"},
  "SC": {"countryName": "Seychelles", "currency": "SCR", "symbol": "SCR"},
  "KZ": {"countryName": "Kazakhstan", "currency": "KZT", "symbol": "KZT"},
  "KY": {"countryName": "Cayman Islands", "currency": "KYD", "symbol": "KYD"},
  "SG": {"countryName": "Singapore", "currency": "SGD", "symbol": "S\$"},
  "SE": {"countryName": "Sweden", "currency": "SEK", "symbol": "Skr"},
  "SD": {"countryName": "Sudan", "currency": "SDG", "symbol": "SDG"},
  "DO": {"countryName": "Dominican Republic", "currency": "DOP", "symbol": "RD\$"},
  "DM": {"countryName": "Dominica", "currency": "XCD", "symbol": "XCD"},
  "DJ": {"countryName": "Djibouti", "currency": "DJF", "symbol": "Fdj"},
  "DK": {"countryName": "Denmark", "currency": "DKK", "symbol": "Dkr"},
  "VG": {"countryName": "British Virgin Islands", "currency": "USD", "symbol": "\$"},
  "DE": {"countryName": "Germany", "currency": "EUR", "symbol": "€"},
  "YE": {"countryName": "Yemen", "currency": "YER", "symbol": "YR"},
  "DZ": {"countryName": "Algeria", "currency": "DZD", "symbol": "DA"},
  "US": {"countryName": "United States", "currency": "USD", "symbol": "\$"},
  "UY": {"countryName": "Uruguay", "currency": "UYU", "symbol": "\$U"},
  "YT": {"countryName": "Mayotte", "currency": "EUR", "symbol": "€"},
  "UM": {
    "countryName": "United States Minor Outlying Islands",
    "currency": "USD",
    "symbol": "\$"
  },
  "LB": {"countryName": "Lebanon", "currency": "LBP", "symbol": "LB£"},
  "LC": {"countryName": "Saint Lucia", "currency": "XCD", "symbol": "XCD"},
  "LA": {"countryName": "Laos", "currency": "LAK", "symbol": "LAK"},
  "TV": {"countryName": "Tuvalu", "currency": "AUD", "symbol": "AU\$"},
  "TW": {"countryName": "Taiwan", "currency": "TWD", "symbol": "NT\$"},
  "TT": {"countryName": "Trinidad and Tobago", "currency": "TTD", "symbol": "TT\$"},
  "TR": {"countryName": "Turkey", "currency": "TRY", "symbol": "TL"},
  "LK": {"countryName": "Sri Lanka", "currency": "LKR", "symbol": "SLRs"},
  "LI": {"countryName": "Liechtenstein", "currency": "CHF", "symbol": "CHF"},
  "LV": {"countryName": "Latvia", "currency": "EUR", "symbol": "€"},
  "TO": {"countryName": "Tonga", "currency": "TOP", "symbol": "T\$"},
  "LT": {"countryName": "Lithuania", "currency": "LTL", "symbol": "Lt"},
  "LU": {"countryName": "Luxembourg", "currency": "EUR", "symbol": "€"},
  "LR": {"countryName": "Liberia", "currency": "LRD", "symbol": "LRD"},
  "LS": {"countryName": "Lesotho", "currency": "LSL", "symbol": "LSL"},
  "TH": {"countryName": "Thailand", "currency": "THB", "symbol": "฿"},
  "TF": {"countryName": "French Southern Territories", "currency": "EUR", "symbol": "€"},
  "TG": {"countryName": "Togo", "currency": "XOF", "symbol": "CFA"},
  "TD": {"countryName": "Chad", "currency": "XAF", "symbol": "FCFA"},
  "TC": {"countryName": "Turks and Caicos Islands", "currency": "USD", "symbol": "\$"},
  "LY": {"countryName": "Libya", "currency": "LYD", "symbol": "LD"},
  "VA": {"countryName": "Vatican", "currency": "EUR", "symbol": "€"},
  "VC": {
    "countryName": "Saint Vincent and the Grenadines",
    "currency": "XCD",
    "symbol": "XCD"
  },
  "AE": {"countryName": "United Arab Emirates", "currency": "AED", "symbol": "AED"},
  "AD": {"countryName": "Andorra", "currency": "EUR", "symbol": "€"},
  "AG": {"countryName": "Antigua and Barbuda", "currency": "XCD", "symbol": "XCD"},
  "AF": {"countryName": "Afghanistan", "currency": "AFN", "symbol": "Af"},
  "AI": {"countryName": "Anguilla", "currency": "XCD", "symbol": "XCD"},
  "VI": {"countryName": "U.S. Virgin Islands", "currency": "USD", "symbol": "\$"},
  "IS": {"countryName": "Iceland", "currency": "ISK", "symbol": "Ikr"},
  "IR": {"countryName": "Iran", "currency": "IRR", "symbol": "IRR"},
  "AM": {"countryName": "Armenia", "currency": "AMD", "symbol": "AMD"},
  "AL": {"countryName": "Albania", "currency": "ALL", "symbol": "ALL"},
  "AO": {"countryName": "Angola", "currency": "AOA", "symbol": "AOA"},
  "AQ": {"countryName": "Antarctica", "currency": "", "symbol": ""},
  "AS": {"countryName": "American Samoa", "currency": "USD", "symbol": "\$"},
  "AR": {"countryName": "Argentina", "currency": "ARS", "symbol": "AR\$"},
  "AU": {"countryName": "Australia", "currency": "AUD", "symbol": "AU\$"},
  "AT": {"countryName": "Austria", "currency": "AUT", "symbol": "€"},
  "AW": {"countryName": "Aruba", "currency": "AWG", "symbol": "AWG"},
  "IN": {"countryName": "India", "currency": "INR", "symbol": "Rs"},
  "AX": {"countryName": "Aland Islands", "currency": "EUR", "symbol": "€"},
  "AZ": {"countryName": "Azerbaijan", "currency": "AZN", "symbol": "man."},
  "IE": {"countryName": "Ireland", "currency": "EUR", "symbol": "€"},
  "ID": {"countryName": "Indonesia", "currency": "IDR", "symbol": "Rp"},
  "UA": {"countryName": "Ukraine", "currency": "UAH", "symbol": "₴"},
  "QA": {"countryName": "Qatar", "currency": "QAR", "symbol": "QR"},
  "MZ": {"countryName": "Mozambique", "currency": "MZN", "symbol": "MTn"}
};
